### ISSUE TITLE
Multi-Export CLI custom filepath issue

### ISSUE THREAD

**Issue by nnra6864** [themix-project/themix-gui#555]
How am I supposed to use the Base16 CLI?
I was doing this till now:
```
/opt/oomox/plugins/theme_oomox/change_color.sh ~/.config/OomoxRicer -o Ricer
/opt/oomox/plugins/icons_suruplus_aspromauros/change_color.sh ~/.config/OomoxRicer -o Ricer
nwg-look -a
```
In order to apply the gtk theme and icons, however, I wanna have the gtk4 support which Base16 appears to have.
So I generated a config, like in the examples I saw:
```yaml
scheme: "Ricer"
author: "nnra"
base00: "ricer.col.background"
base01: "ricer.col.background_alt"
base02: "ricer.col.background_highlight"
base03: "ricer.col.foreground_inactive"
base04: "ricer.col.foreground_alt"
base05: "ricer.col.foreground"
base06: "ricer.col.foreground_highlight"
base07: "ricer.col.background_highlight"
base08: "ricer.col.br_red"
base09: "ricer.col.yellow"
base0A: "ricer.col.br_yellow"
base0B: "ricer.col.br_green"
base0C: "ricer.col.br_cyan"
base0D: "ricer.col.br_blue"
base0E: "ricer.col.br_magenta"
base0F: "ricer.col.foreground_highlight"
```
And I just can't figure out how to apply it via CLI.
